import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layouts/Navbar";
import Footer from "@/components/Layouts/Footer";
import TopBar from "@/components/TopBar/TopBar";

const poppins = Rubik({
  weight: ['300','400','500','600','700','800','900'],
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Clover Clothing",
    template: "%s | Clover Clothing",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.className} antialiased bg-gray-200`}>
        <header className=" md:w-full gap-0 mx-auto">
          <TopBar/>
          <Navbar />
        </header>

        <main  className="px-5 py-2 md:w-11/12 mx-auto min-h-[calc(100vh-330px)]">
          {children}
        </main>
        

        

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}